TYPO3:
  Neos:
    typoScript:
      autoInclude:
        'Shel.DynamicNodes': TRUE

    modules:
      management:
        submodules:
          dynamicNodeTypes:
            label: 'Manage dynamic node types'
            controller: '\Shel\DynamicNodes\Controller\DynamicNodeTypeController'
            description: "This module allows to manage dynamic node types which can be used by edtiors"
            icon: 'icon-sitemap'

    nodeTypes:
      groups:
        dynamicNodes:
          position: 100
          label: 'Dynamic node types'

Shel:
  DynamicNodes:
    defaults:
      nodeNamespace: 'Shel.DynamicNodes'
      nodeNamePrefix: 'DynamicNode'
      propertyPrefix: 'dynamicProperty'
      superTypes:
        - 'Shel.DynamicNodes:DynamicNode'
